//MANAGER TYPES
export const SETINVOICETABLE = "SETINVOICETABLE"
export const SETINVOICEDATA =  "SETINVOICEDATA"
export const SETOPENPDF = "SETOPENPDF"
export const CREATE_PURCHASE = "CREATE_PURCHASE"
export const GET_PURCHASE_INVOICE = "GET_PURCHASE_INVOICE"
export const CREATE_SALES = "CREATE_SALES"
export const GET_SALES_INVOICE = "GET_SALES_INVOICE"
export const GET_INV_KEY = "GET_INV_KEY"
export const GET_S_KEY = "GET_INV_KEY"
export const GET_SUPLIERS = "GET_SUPLIERS"
export const ADD_SUPLIER = "ADD_SUPLIER"
export const GET_CUSTOMER = "GET_CUSTOMER"
export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const ADD_CATEGORIES = "ADD_CATEGORIES"
export const GET_CATEGORIES = "GET_CATEGORIES"
export const ADD_PRODUCT = "ADD_PRODUCT"
export const GET_PRODUCTS= "GET_PRODUCTS"
//ADMIN TYPES

// export const OPEN_FILTER_MODAL = 'OPEN_FILTER_MODAL'
// export const CLOSE_FILTER_MODAL = 'CLOSE_FILTER_MODAL'
export const OPEN_EDIT_MEMBER_MODAL = 'OPEN_EDIT_MEMBER_MODAL'
export const CLOSE_EDIT_MEMBER_MODAL = 'CLOSE_EDIT_MEMBER_MODAL'
export const OPEN_SOFTWARE_HOUSE_MODAL = 'OPEN_SOFTWARE_HOUSE_MODAL'
export const CLOSE_SOFTWARE_HOUSE_MODAL = 'CLOSE_SOFTWARE_HOUSE_MODAL'
export const GET_ORGANIZATION_DATA = 'GET_ORGANIZATION_DATA '
export const SET_CURRENT_ORGANIZATION = 'SET_CURRENT_ORGANIZATION'
export const GET_MEMBERS = 'GET_MEMBERS'
export const SET_CURRENT_MEMBER = 'SET_CURRENT_MEMBER'
export const FILTER_MEMBER = 'FILTER_MEMBER'
export const FILTER_ORGANIZATION = 'FILTER_ORGANIZATION'
export const CLEAR_FILTER = 'CLEAR_FILTER'

//USERS

export const SET_USER_DATA = 'SET_USER_DATA'  //LogIn
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
export const USER_LOG_OUT = 'USER_LOG_OUT'
export const USER_SIGN_UP = 'USER_SIGN_UP'  //katana hai
export const GET_PROJECTS = 'GET_PROJECTS'
export const GET_CLICKED_PROJECT = 'GET_CLICKED_PROJECT'
export const OPEN_VIEW_TASK_MODAL = 'OPEN_VIEW_TASK_MODAL'
export const CLOSE_VIEW_TASK_MODAL = 'CLOSE_VIEW_TASK_MODAL'
export const SET_PROJECT_PERCENTAGE = 'SET_PROJECT_PERCENTAGE'
export const SHOW_PROFILE_FLAG = 'SHOW_PROFILE_FLAG'
export const CLOSE_PROFILE_FLAG = 'CLOSE_PROFILE_FLAG'
export const SET_TASK_STATUS = 'SET_TASK_STATUS'
export const ALERT = 'ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const SET_LOADING = 'SET_LOADING'


//DASHBOARD 
export const DASHBOARD = "DASHBOARD";